apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: patch-argocd-notifications-cm
spec:
  serviceAccountName: argo-workflows-sa
  entrypoint: patch-cm
  templates:
    - name: patch-cm
      container:
        image: bitnami/kubectl:1.28.5
        command: [sh, -c]
        args:
          - |
            kubectl patch configmap argocd-notifications-cm -n argocd --type=json -p="[{\"op\": \"replace\", \"path\": \"/data\", \"value\": {}}]"
          #  for cm in $(kubectl get configmap -n cmdo-argocd-notifications -l argocd.argoproj.io/instance=argocd-notifications -o jsonpath='{.items[*].metadata.name}'); do
          #    echo $cm;
          #    cm_data=$(kubectl get configmap $cm -n cmdo-argocd-notifications -o jsonpath='{.data}')
          #    kubectl patch configmap argocd-notifications-cm -n argocd --type merge -p "{\"data\": $cm_data}" -o yaml
          #  done;
          # kubectl patch configmap argocd-notifications-cm -n argocd --type=json -p="[{\"op\": \"replace\", \"path\": \"/data\", \"value\": {}}]"



