apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: post-deploy-github-action
  namespace: argo
spec:
  serviceAccountName: argo-workflows-sa
  entrypoint: post-action

  templates:
  - name: post-action
    steps:
    - - name: use-secret
        template: secret-task
  
  - name: secret-task
    conatainer:
      image: bitnami/kubectl:1.28.5
      command: ["sh", "-c"]
      args:
        - |
          echo "The password is: PAT_GITHUB;
      #env:
      #  - name: PAT_GITHUB
      #    valueFrom:
      #      secretKeyRef:
      #        name: post-deploy-secret
      #        key: pat-github

    #- name: post-action
    #  container:
    #    image: bitnami/kubectl:1.28.5
    #    command: [sh, -c]
    #    args:
    #      - |
    #        APP="{{inputs.parameters.app-name}}"
    #        TOKEN="{{inputs.parameters.github-token}}"
    #        NS="argocd"
    #
    #        DEPLOY=$(kubectl get application "$APP" -n "$NS" -o jsonpath="{.status.resources[?(@.kind=='Deployment')].name}")
    #        IMAGE=$(kubectl get deployment "$DEPLOY" -n "$NS" -o jsonpath="{.spec.template.spec.containers[0].image}")
    #        TAG="${IMAGE##*:}"
    #
    #        echo "App: $APP | Deploy: $DEPLOY | Image: $IMAGE | Tag: $TAG"
    #
    #        curl -X POST \
    #          -H "Authorization: token $TOKEN" \
    #          -H "Accept: application/vnd.github+json" \
    #          https://api.github.com/repos/<org>/<repo>/actions/workflows/<workflow_file.yml>/dispatches \
    #          -d "{\"ref\": \"main\", \"inputs\": {\"image_tag\": \"$TAG\"}}"



