apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: post-deploy-github-action-template
spec:
  serviceAccountName: argo-workflows-sa
  entrypoint: post-deploy-github-action

  arguments:
    parameters:
    - name: app-name

  templates:
  - name: post-deploy-github-action
    steps:
    - - name: get-tag
        template: get-tag-task
        arguments:
          parameters:
          - name: app-name
            value: "{{workflow.parameters.app-name}}"
    - - name: post-action
        template: post-action-task
        arguments:
          parameters:
          - name: image-tag
            value: "{{steps.get-tag.outputs.parameters.result}}" 
  

  - name: get-tag-task
    inputs:
      parameters:
      - name: app-name
    outputs:
        parameters:
          - name: result
            valueFrom:
              path: /tmp/tag.txt
    container:
      image: bitnami/kubectl:1.28.5
      command: [sh, -c]
      args:
        - |
          APP="{{inputs.parameters.app-name}}"
          APP_NS="argocd"
          TARGET_NS=$(kubectl get application "$APP" -n "$APP_NS" -o jsonpath="{.spec.destination.namespace}")
          DEPLOY=$(kubectl get application "$APP" -n "$APP_NS" -o jsonpath="{.status.resources[?(@.kind=='Deployment')].name}")
          IMAGE=$(kubectl get deployment "$DEPLOY" -n "$TARGET_NS" -o jsonpath="{.spec.template.spec.containers[0].image}")
          TAG="${IMAGE##*:}"  
          echo "$TAG"
          echo "$TAG" > /tmp/tag.txt

  - name: post-action-task
    inputs:
      parameters:
      - name: image-tag
    container:
      image: curlimages/curl:8.13.0
      command: [sh, -c]
      args:
        - |
          curl -X POST \
            -H "Authorization: $PAT_GITHUB" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/devopsYo/apigee/actions/workflows/github-actions-demo.yml/dispatches \
            -d "{\"ref\": \"main\", \"inputs\": {\"swagger_app_name\": \"{{inputs.parameters.image-tag}}\"}}"
      env:
        - name: PAT_GITHUB
          valueFrom:
            secretKeyRef:
              name: post-deploy-secret
              key: pat-github


